name: Kubelet Go Modules
description: Kubelet Go Module Logging Sources
enabled: true
queryString: |-
  SYSLOG_IDENTIFIER=kubelet _HOSTNAME=* MESSAGE=*
  | regex("^(?<syslog_header>[^\"]+)\"(?<syslog_message>[^\"]+)\"(?<syslog_message_kv>.+)",field=MESSAGE)
  | regex("^(?<msgid>\S+)\s(?<mtime>\S+)\s+(?<mn>\d+)\s(?<gomodule>[_a-z0-9]+\.go:\d+)\]",field=syslog_header)
  | case { msgid = "I*" | msg_severity := "INFO";
           msgid = "W*" | msg_severity := "WARN";
           msgid = "E*" | msg_severity := "ERROR";
           *            | msg_severity := "UNKNOWN"}
  | msg_severity=*
  | regex("^(?<go_module>[^:]+):\d+",field=gomodule)
  | groupBy(field=go_module, function=count())
  | table([go_module])
backfillLimit: 0
schedule: '*/5 * * * *'
queryEnd: now
$schema: https://schemas.humio.com/scheduledsearch/v0.1.0
timeZone: UTC+00:00
queryStart: 7d
actionNameReferences:
- Kublet Go Modules Lookup
