name: fluentbit
tests:
- '{"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"Metadata","auditID":"18c8b1b9-231d-4d5d-8b27-0427ff6568e9","stage":"ResponseComplete","requestURI":"/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/kube-controller-manager?timeout=5s","verb":"update","user":{"username":"system:kube-controller-manager","groups":["system:authenticated"]},"sourceIPs":["10.169.31.183"],"userAgent":"kube-controller-manager/v1.26.0
  (linux/amd64) kubernetes/b46a3f8/leader-election","objectRef":{"resource":"leases","namespace":"kube-system","name":"kube-controller-manager","uid":"ee582fba-fadd-41c3-922f-2d7347c2bd7e","apiGroup":"coordination.k8s.io","apiVersion":"v1","resourceVersion":"30093799"},"responseStatus":{"metadata":{},"code":200},"requestReceivedTimestamp":"2023-07-28T18:40:57.435352Z","stageTimestamp":"2023-07-28T18:40:57.437856Z","annotations":{"authorization.k8s.io/decision":"allow","authorization.k8s.io/reason":"RBAC:
  allowed by ClusterRoleBinding \"system:kube-controller-manager\" of ClusterRole
  \"system:kube-controller-manager\" to User \"system:kube-controller-manager\""}}'
fieldsToBeRemovedBeforeParsing: []
$schema: https://schemas.humio.com/parser/v0.2.0
script: |-
  case {
      // parse using embedded timestamp
      flb.source="container" | parseJson() | parseTimestamp(field=time);
      flb.source="audit" | parseJson() | parseTimestamp(field=requestReceivedTimestamp);
      // systemd sources
      flb.source="systemd" | parseJson() | SYSLOG_IDENTIFIER match {
          // ("dockerd", "containerd") Timestamp (time) contained in MESSAGE KV
          in(values=["dockerd","containerd"]) => kvParse(field=MESSAGE) | parseTimestamp(field=time);
          // ("kubelet")  Timestamp (flb.time) added by fluent-bit
          in(values=["kubelet"]) => parseTimestamp(field=flb.time,format="seconds")
      };
      // parse using fluent-bit timestamp
      flb.source=* | parseJson() | parseTimestamp(field=flb.time,format="seconds")
  }
tagFields: []
