name: kv-generic
tests:
- 109.169.248.247 - - [12/Dec/2015:18:25:11 +0100] "GET /administrator/ HTTP/1.1"
  200 4263 "-" "Mozilla/5.0 (Windows NT 6.0; rv:34.0) Gecko/20100101 Firefox/34.0"
  "-"
- <34>1 2003-10-11T22:14:15.003Z mymachine.example.com su - ID47 - BOM'su root' failed
  for lonvick on /dev/pts/8
- '<12>Jan  3 12:14:41 dpinger: GW_VeeamPN 172.16.100.200: sendto error: 64'
- 'May 11 10:40:48 scrooge disk-health-nurse[26783]: [ID 702911 user.error] m:SY-mon-full-500
  c:H : partition health measures for /var did not suffice - still using 96% of partition
  space'
- '{"@path":"x509","@sensor":"host-sensor","@timestamp":"2019-06-01T02:57:39.982467Z","ts":"2019-06-01T02:57:39.982467Z","id":"FJyS8D2AI1cHajXbMg","certificate.version":3,"certificate.serial":"0394BF7C616948D34169AA51CE3A4BFCC76C","certificate.subject":"CN=cloud.humio.com","certificate.issuer":"CN=Let''s
  Encrypt Authority X3,O=Let''s Encrypt,C=US","certificate.not_valid_before":"2019-05-16T03:11:23.000000Z","certificate.not_valid_after":"2019-08-14T03:11:23.000000Z","certificate.key_alg":"rsaEncryption","certificate.sig_alg":"sha256WithRSAEncryption","certificate.key_type":"rsa","certificate.key_length":2048,"certificate.exponent":"65537","san.dns":["cloud.humio.com"],"basic_constraints.ca":false}'
- '{"Timestamp":"2019-01-18T13:06:53.3642110+01:00","Level":"Information","MessageTemplate":"Number
  of user sessions {@UserSessions}","RenderedMessage":"Number of user sessions 103","Properties":{"UserSessions":103,"ProcessId":"8009"}}'
- '[Fri Sep 09 10:42:29.902022 2011] [core:error] [pid 35708:tid 4328636416] [client
  72.15.99.187] File does not exist: /usr/local/apache2/htdocs/favicon.ico'
- 2018-10-15T12:52:42+01:30 [ERROR] Here is an error log entry. class=c.o.StringUtil
  fruit=pineapple
- 1286536309.549    172 192.168.0.227 TCP_MISS/204 294 GET http://v15.lscache3.c.youtube.com/generate_204?
  - DIRECT/122.160.120.150 text/html
- Log format with compact date/time format 20121102143402781
fieldsToBeRemovedBeforeParsing: []
$schema: https://schemas.humio.com/parser/v0.2.0
script: kvParse(@rawstring) | findTimestamp(timezone=UTC)
tagFields: []
